#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /usr/bin/chromium 100
    update-alternatives --install /usr/bin/gnome-www-browser \
        gnome-www-browser /usr/bin/chromium 100
fi
